apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "kubecoin.labels" . | nindent 4 }}
spec:
  type: ExternalName
  {{ if .Values.redisEndpoint }}
  externalName: '{{ .Values.redisEndpoint }}'
  {{ else }}
  externalName: '{{ include "kubecoin.redis.service" . }}.{{ .Release.Namespace }}.{{ default "svc.cluster.local" .Values.global.clusterDNS }}'
  {{ end }}
  ports: []
